language: php
php:
  - 5.3
  - 5.4

before_script:
  - php app/Resources/data/travis-build.php
  - curl -s http://getcomposer.org/installer | php
  - COMPOSER_ROOT_VERSION=dev-master php composer.phar --dev install
  - php app/console doctrine:database:create
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load

script: phpunit -c app/phpunit.xml