imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

tickit_cache:
    default_namespace: "tickit.cache"
    types:
        file:
            auto_serialize: true
            default_path: /tmp
            directory_base: test_cache
        apc: true