imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        user:     %test_database_user%
        path:     %kernel.cache_dir%/sqlite
        charset:  UTF8

#TickitCacheBundle configuration
tickit_cache:
    default_namespace: "tickit.test"
    types:
        file:
            auto_serialize: true
            default_path: "%kernel.cache_dir%/tickit_cache"
        memcached:
            persistence_id: tickit
            servers:
                main:
                    host: localhost
                    name: main
                    weight: 100
                    retry_time: 5
                    enabled: true
                alternate:
                    name: alternate
                    host: localhost
                    weight: 0
                    port: 11211
                    retry_time: 10
                    enabled: true