# TeamBundle Routes

team_show:
  pattern: /teams/{id}
  defaults: { _controller: TickitTeamBundle:Team:edit }
  requirements:
    _method: GET

team_update:
  pattern: /teams/{id}/update
  defaults: { _controller: TickitTeamBundle:Team:update }
  requirements:
    _method: POST

team_new:
  pattern: /teams/new
  defaults: { _controller: TickitTeamBundle:Team:new }
  requirements:
      _method: GET

team_create:
  pattern: /teams/create
  defaults: { _controller: TickitTeamBundle:Team:create }
  requirements:
    _method: POST

team_index:
  pattern: /teams/{page}
  defaults: { _controller: TickitTeamBundle:Team:index, page: 1 }
  requirements:
    page: \d+