project_index:
    pattern: /{page}
    defaults: { _controller: TickitProjectBundle:Project:index, page: 1 }
    requirements:
        page: \d+

project_create:
    pattern: /create
    defaults: { _controller: TickitProjectBundle:Project:create }

project_edit:
    pattern: /edit/{id}
    defaults: { _controller: TickitProjectBundle:Project:edit }
    requirements:
        id: \d+

project_delete:
    pattern: /delete/{id}
    defaults: { _controller: TickitProjectBundle:Project:delete }
    requirements:
        id: \d+

project_attribute_index:
    pattern: /attributes/{page}
    defaults: { _controller: TickitProjectBundle:Attribute:index, page: 1 }
    requirements:
        page: \d+

project_attribute_create:
    pattern: /attributes/{type}/create
    defaults: { _controller: TickitProjectBundle:Attribute:create }

project_attribute_edit:
    pattern: /attributes/edit/{id}
    defaults: { _controller: TickitProjectBundle:Attribute:edit }
    requirements:
        id: \d+

project_attribute_delete:
    pattern: /attributes/delete/{id}
    defaults: { _controller: TickitProjectBundle:Attribute:delete }
    requirements:
        id: \d+
