project_index:
    pattern: /{page}
    defaults: { _controller: TickitProjectBundle:Project:index, page: 1 }
    requirements:
        page: \d+

project_add:
    pattern: /add
    defaults: { _controller: TickitProjectBundle:Project:add }

project_edit:
    pattern: /edit/{id}
    defaults: { _controller: TickitProjectBundle:Project:edit }
    requirements:
        id: \d+

project_delete:
    pattern: /delete/{id}
    defaults: { _controller: TickitProjectBundle:Project:delete }
    requirements:
        id: \d+

project_attribute_add:
    pattern: /attribute/{type}/add
    defaults: { _controller: TickitProjectBundle:Attribute:add }