Tickit\ProjectBundle\Entity\Project:
    properties:
        name:
            - MaxLength: { limit: 100, message: "Name is too long, try something a little shorter (100 characters max)" }
            - NotBlank: { message: "You didn't provide a name, did you forget it?" }
