Tickit\ProjectBundle\Entity\Project:
    properties:
        name:
            - MaxLength: { limit: 100, message: "Project name must be less than 100 characters" }
            - NotBlank: { message: "Please enter a project name" }
