services:
  login_listener:
    class: Tickit\UserBundle\Listener\Login
    arguments: [@service_container, @session, @doctrine, @permissions]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
  activity_listener:
    class: Tickit\UserBundle\Listener\Activity
    arguments: [@security.context, @doctrine]
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
  avatar:
    class: Tickit\UserBundle\Service\Avatar\AvatarService
    arguments: [@request, "%tickit_user.avatar.adapter_class%"]
    scope: request
  avatar_twig_extension:
    class: Tickit\UserBundle\Service\Avatar\Twig\AvatarExtension
    tags:
      - { name: twig.extension }
    arguments: [@service_container,@security.context]