services:
  login_listener:
    class: Tickit\UserBundle\Listener\Login
    arguments: [@service_container, @session, @doctrine]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
  activity_listener:
    class: Tickit\UserBundle\Listener\Activity
    arguments: [@security.context, @doctrine]
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }